apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: detect-cryptominer
spec:
  kprobes:
    - call: "sys_execve"
      syscall: true
      args:
        - index: 0
          type: "string"
      selectors:
        - matchBinaries:
            - operator: "In"
              values:
                - "/usr/local/bin/node"
                - "/usr/bin/node"
          matchArgs:
            - index: 0
              operator: "Postfix"
              values:
                - "/miner-stub"
